### PR TITLE
Multinode Objectstorage

### PR DESCRIPTION
**Pull request by mephenor**
Adapted config to use multinode object storage
Tests use two different s3 fixtures now based on this config
Bumped to 1.0.0

### CODE REVIEW

**Review by KerstenBreuer — DISMISSED** [review]
Looks very nice. Could not find an issue.

**Review by Cito — APPROVED** [review]

**Review by Cito — CHANGES_REQUESTED** [review]
Would this not cause problems again when the s3 alias is sent in the payload?

**Review by Cito — COMMENTED** [review]
That was the problem detected in the archive test bed.

**Comment by mephenor** [comment]
This should fix communication between the IRS and DCS in the latest version [1.1.0](https://github.com/ghga-de/download-controller-service/releases/tag/1.1.0).
The only thing currently not up to date should be the producers for the FileUploadValidationSuccess event, i.e. the interrogation room and file ingest services, which are next on the list for refactoring.
I started working on the IRS, but adapting FIS first would probably make more sense for the testbed, just need to get the kuberenetes stuff there merged first.

I could also just add a hardcoded endpoint alias in the meantime, would probably make sense for FIS either way as there's currently no selection logic, so a simple config option or something along those lines should be good enough for now.

**Review by Cito — APPROVED** [review]
Ok, will try the integration tests with the latest versions of all services again and see if it works.

**Pull request merged**
